default:
    # image: cmdlabs/musketeers # Used for bootstrapping the repo below.
    image: lastknight.jfrog.io/lastknight/multicicd

services:
    - docker:dind

stages:
    - build

build:
    stage: build
    script: make docker-publish
