default:
    image: cmdlabs/musketeers

services:
    - docker:dind

stages:
    - build
    - publish

build:
    stage: build
    script:
        - ls -la
        - make docker-build

publish:
    stage: publish
    script: 
        - make docker-publish
